version: '3'
services:
  smartcredit_server:
    build: ./
    env_file: .env
    ports:
      - "41337:41337"

  rinkeby:
    image: ethereum/client-go
    command: '--datadir=/root/data --rinkeby --fast --rpc --rpcaddr="0.0.0.0" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*"'
    volumes:
      - ./datadir/:/root/data:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"